name: Version Bump and Tag

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get PR title for version bump
        id: get_version_type
        run: |
          # Get the latest merge commit to find the associated PR
          MERGE_COMMIT=$(git log -1 --pretty=%H)

          # Get PR number from merge commit message (GitHub format: "Merge pull request #123")
          PR_NUMBER=$(git log -1 --pretty=%B | grep -o "Merge pull request #[0-9]*" | grep -o "[0-9]*" || echo "")

          VERSION_TYPE="patch"  # Default to patch

          if [ -n "$PR_NUMBER" ]; then
            # Fetch PR title using GitHub API
            PR_TITLE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | \
              jq -r '.title // empty')
            
            echo "PR #$PR_NUMBER title: $PR_TITLE"
            
            # Extract version type from PR title
            if echo "$PR_TITLE" | grep -q "\[version:major\]"; then
              VERSION_TYPE="major"
            elif echo "$PR_TITLE" | grep -q "\[version:minor\]"; then
              VERSION_TYPE="minor"
            elif echo "$PR_TITLE" | grep -q "\[version:patch\]"; then
              VERSION_TYPE="patch"
            fi
          else
            echo "No PR number found in merge commit, using default patch version"
          fi

          echo "type=$VERSION_TYPE" >> $GITHUB_OUTPUT
          echo "Version bump type: $VERSION_TYPE"

      - name: Bump version
        run: |
          VERSION_TYPE=${{ steps.get_version_type.outputs.type }}
          npm version $VERSION_TYPE --no-git-tag-version

          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "🚀 (Release) Bump Version: v${{ env.NEW_VERSION }} [skip ci]"
          git push origin master

      - name: Create and push Git tag
        run: |
          git tag -a "v${{ env.NEW_VERSION }}" -m "Release v${{ env.NEW_VERSION }}"
          git push origin "v${{ env.NEW_VERSION }}"

      - name: Create GitHub Release (optional)
        run: |
          gh release create "v${{ env.NEW_VERSION }}" \
            --title "Release v${{ env.NEW_VERSION }}" \
            --notes "Automated release v${{ env.NEW_VERSION }}" || echo "GitHub CLI not available or release already exists"
